### PR TITLE
Various fixes for labels check

### LINKED ISSUE #455: Tags
I enabled "Approval Check" (and only this function so far) for my repository but now pull request shows not only "Approvals check" (which is expected) but also following
> Some checks haven’t completed yet
> 1 expected and 1 pending checks
> Required  zappr/pr/labels — Waiting for status to be reported 

1. On GitHub Enterprise I see no configuration options that would allow me to change tags
2. "Effective configuration" in Zappr does not seem to contain "tags" relevant config
3. When I try to enable "Tags" function (which is currently disabled) it says that

> Error during check processing
> Check pullrequestlabels already exists for repository 4793.

So now "tags" check prevents me from merging request and I have no Idea how to work around this except disabling Zappr for my repository.

### PR DESCRIPTION
**Pull request by prayerslayer**
* First try to enable the check, afterwards set branch protection
* Add migration for missing enum value
* Properly use default values

Fixes #455

### CODE REVIEW

**Comment by neremic** [comment]
:+1:

**Comment by harti2006** [comment]
:+1:

File: migrations/004-add-prlabels-enum-value.js [hunk 1]
```diff
@@ -0,0 +1,12 @@
+module.exports.up = function up(queryInterface) {
+  if (queryInterface.sequelize.options.dialect === 'postgres') {
+    // alter enum type
+    return queryInterface.sequelize.query(`ALTER TYPE zappr_data.enum_checks_type ADD VALUE IF NOT EXISTS 'pullrequestlabels';`)
+  }
+  // for sqlite we do not care as it is used for development
+  return Promise.resolve()
+}
+module.exports.down = function down() {
+  // there is no good downgrade
```
Comment (gagoman) [inline migrations/004-add-prlabels-enum-value.js]: Do we need to alert somehow and not just resolve promise?

Comment (prayerslayer) [inline migrations/004-add-prlabels-enum-value.js]: We could, I guess. But since I found no easy way to safely remove a value from an enum type, I'm not sure what would be gained. You would get a warning you can't do anything about?
