### PR TITLE
146 - Show zappr status as 'In progress' when having too few approvals

### LINKED ISSUE #146: Show zappr status as "In progress" when having too few approvals
Is it possible to mark a pull request, that has not yet received enough approvals, as "In progress" (yellow dot) instead of "Failed"? It always looks like something really went wrong, when I see that red cross on my commits / pull requests.

### PR DESCRIPTION
**Pull request by spaudanjo**
fixes #146

### CODE REVIEW

File: server/checks/Approval.js [hunk 1]
```diff
@@ -121,19 +121,19 @@ export default class Approval extends Check {
           if (action === 'opened' && minimum > 0) {
             // if it was opened, set to fail
```
Comment (prayerslayer) [inline server/checks/Approval.js]: Could you also update the comments? 😅

**Comment by prayerslayer** [comment]
:+1:

**Comment by spaudanjo** [comment]
👍
