### PR TITLE
Fix forever spinning toggles in error case

### LINKED ISSUE #241: Toggles spinning infinitely in case of error
When you toggle a check but it does not work for whatever reason, the toggle do not go back to "not toggled" state, but keep spinning.

### PR DESCRIPTION
**Pull request by prayerslayer**
Fixes #241 

Problem was that the payload in case of error did not have a `checkId` set.

### CODE REVIEW

File: client/actions/checks.js [hunk 1]
```diff
@@ -20,12 +20,20 @@ function deleteCheck(status, payload = null) {
...
 }
 
+function constructError(check, error) {
+  return {
+    ...error,
+    message: error.message,
+    checkId: check.checkId
+  }
+}
+
```
Comment (mfellner) [inline client/actions/checks.js]: Another option would be to use a custom error class, ES6 style. What do you think? 😄

Comment (prayerslayer) [inline client/actions/checks.js]: Probably a bit nicer, yes.

Comment (mfellner) [inline client/actions/checks.js]: Your call, we can refactor this later if we want to use custom errors more widely.

**Comment by mfellner** [comment]
👍

File: client/actions/checks.js (hunk 1 above)
Comment (prayerslayer) [inline client/actions/checks.js]: Yay, later! 😁
